builds:
  - binary: check-dns-multi
    main: ./cmd/check-dns-multi
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: monitoring-forge
    name: check-dns-multi
